### PR TITLE
Adding blurbs to pages issue 5286

### PR DESCRIPTION
**Pull request by MatthewMcP**
Relates to
https://github.com/HabitRPG/habitrpg/issues/5286#

### CODE REVIEW

**Comment by hairlessbear** [comment]
Hi! Am I correct in assuming that you are trying to submit this pull request to HabitRPG? If so, you've made a slight error: this pull request is submitted to your copy of the repository, not HabitRPG's repository. As in, the HabitRPG developers won't see this, and can't merge it into the main `develop` repository. Would you like some help getting this moved to the proper repository?

**Comment by MatthewMcP** [comment]
Yeah I was trying to... Help would be appreciated, although I won't have a chance to look at this again until Sunday

**Comment by hairlessbear** [comment]
The process to get this over to HabitRPG is actually pretty simple.
1. Merge this Pull Request into your repository. You can do this from this page by clicking the "Merge" button
2. Go to https://github.com/HabitRPG/habitrpg
3. There should be a button right above the file list, that looks something like this:
selection_002
4. Click the "Compare & Pull Request" button.
5. Add screenshots for each page you changed and a description of your work (include the text "Fixes #5286" so the original issue is referenced)
6. Click "Create Pull Request" 

That's it! If anything is unclear, let me know.

**Comment by MatthewMcP** [comment]
Hmm I'm still having issues. I can't see the "compare and pull request" button on  https://github.com/HabitRPG/habitrpg.

I can create a pull request between branches on my fork (https://github.com/MatthewMcP/habitrpg) but I can't see a way to  create a pull request from my fork to https://github.com/HabitRPG/habitrpg.

I tried to create a branch on https://github.com/HabitRPG/habitrpg. but was getting a permission denied error.

**Comment by hairlessbear** [comment]
I think I see the issue: when you forked, I don't believe you added the main repository as an upstream. This is necessary for git to track changes between your fork and the base repository. The easiest way to check this is by typing `git remote -v` on your command line. If I'm right, your output will look something like this:
```
origin	https://github.com/hairlessbear/habitrpg.git (fetch)
origin	https://github.com/hairlessbear/habitrpg.git (push)
```

But it should look like this:
```
origin	https://github.com/hairlessbear/habitrpg.git (fetch)
origin	https://github.com/hairlessbear/habitrpg.git (push)
upstream	https://github.com/HabitRPG/habitrpg.git (fetch)
upstream	https://github.com/HabitRPG/habitrpg.git (push)
```

Fortunately, this is easy to fix. From the command line, run the command 
```
git remote add upstream https://github.com/HabitRPG/habitrpg.git
``` 
Verify that the command worked by typing `git remote -v` and making sure your output looks similar to the example above.

Assuming that all works fine, there's another issue we need to take care of. You did this work over a week ago, so your repository is out of date with the main one. Here's how to fix this:

1. From the command line, switch to your branch by typing `git checkout Adding-Blurbs-to-page`
2. Then type `git fetch upstream`. This fetches (i.e., downloads) the most recent version of the repository, but doesn't make any changes to the files in your repository
3. Type `git merge upstream/develop`. This will merge in the work you've done with the most recent repository. Since the changes you made are pretty simple, I don't think there will be any merge conflicts. If there are, let me know, and we'll work through them.
4. Type `git push` to push the changes to your branch

Once you do this, you should be able to follow the instructions from my last message. But, just in case that doesn't work, here's another method which should also work. 

1. Go to your fork (https://github.com/MatthewMcP/habitrpg)
2. Click the green button in the below picture (it says "Compare, review, create a pull request" when you hover your mouse over it). **IMPORTANT**: at this stage, you may be presented the option to create a pull request. Don't do that yet. That will create a pull request from your `develop` branch, which we don't want. We want to create a pull request from your `Adding-Blurbs-to-page` branch.
selection_006
This will bring you to a page that looks like this:
selection_007
3. Click on the rightmost dropdown (the one that starts with the text "compare:")
4. Select (or type in) the name of your branch
selection_008
5. Once you select your branch, you should be on a page that looks like this:
selection_009
6. Click the "Create pull request" button, which will open up a text box that allows you to add screenshots and a description.
7. Once you add all of the pertinent information, click "Create pull request", and you're done!

**Comment by hairlessbear** [comment]
Oops, I made a slight error. If you're reading these via email, please view my previous message on GitHub to see the corrected version.

**Comment by MatthewMcP** [comment]
I can't seem to get habitRPG/habitrpg to show as my base fork.
untitled
I do have habitrpg as my upstream, am I missing something?
image

**Comment by hairlessbear** [comment]
Hmm...something's definitely off. When you look at your repository page, you should see a message informing you of the status of your branch when compared with the base repository. Like this (this is from my fork):
selection_010

Your page doesn't display that message, for some reason. Whatever's causing that is likely the same thing making you unable to get HabitRPG/habitrpg as your base fork.

How did you create your fork originally? There might have been an issue there that caused this. Did you basically follow [these instructions](http://habitrpg.wikia.com/wiki/Setting_up_HabitRPG_locally#Fork_.26_Clone_HabitRPG_.28All_Operating_Systems.29)?

**Comment by hairlessbear** [comment]
This might be the issue: did you press the "fork" button to create your repository, or did you use a different method?

**Comment by MatthewMcP** [comment]
I can't remember to be honest. I tried the fork button and I'm now seeing it as it is in your screenshots. Going to copy over my code, test it, then try to create a pull request.

**Comment by hairlessbear** [comment]
Awesome, I think that'll fix it.

I'm pretty sure what happened is that you cloned the repository instead of forking it. That gave you all of the code, but didn't create the necessary connections to the original repository to create pull request.

**Pull request merged**
